//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketSalesEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.TiketsCount = 1;
        }
    
        public int OrderId { get; set; }
        public int TiketsCount { get; set; }
        public System.TimeSpan OrderTime { get; set; }
        public int SeanceSeanceId { get; set; }
    
        public virtual Seance SeanceId { get; set; }
    }
}
